import Modal from "@/components/Modal";
import { dark } from "@clerk/themes";
import { ClerkProvider, SignIn } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Listify",
  description: "Generated by SushrutNetkar",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-[#e8e3e4]">
          {children}
          <Modal />
        </body>
      </html>
    </ClerkProvider>
  );
}
